In [1]:
import pandas as pd

In [5]:
supermarket = pd.DataFrame({
    'item':['Banana', 'Cucumber', 'Orange', 'Tomato', 'Watermelon'],
    'Type':['Fruit', 'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
    'Price':[0.99, 1.25, 0.25, 0.33, 3.00]
})
supermarket.head()

         item       Type  Price
0      Banana      Fruit   0.99
1    Cucumber  Vegetable   1.25
2      Orange      Fruit   0.25
3      Tomato  Vegetable   0.33
4  Watermelon      Fruit   3.00

In [8]:
groups = supermarket.groupby('Type')
groups

In [9]:
groups.get_group('Fruit')

         item   Type  Price
0      Banana  Fruit   0.99
2      Orange  Fruit   0.25
4  Watermelon  Fruit   3.00

In [10]:
groups.get_group('Vegetable')

       item       Type  Price
1  Cucumber  Vegetable   1.25
3    Tomato  Vegetable   0.33

In [22]:
groups.mean(numeric_only=True)

              Price
Type
Fruit      1.413333
Vegetable  0.790000

In [24]:
fortune = pd.read_csv('fortune1000.csv')
fortune.head()

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care

In [26]:
fortune[fortune['Sector']=='Retailing']

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
7,Amazon.com,177866.0,3033.0,566000,Retailing,Internet Services and Retailing
14,Costco,129025.0,2679.0,182000,Retailing,General Merchandisers
22,Home Depot,100904.0,8630.0,413000,Retailing,Specialty Retailers: Other
38,Target,71879.0,2934.0,345000,Retailing,General Merchandisers
...,...,...,...,...,...,...
909,99 Cents Only Stores,2194.0,-90.3,17200,Retailing,Specialty Retailers: Other
926,Express,2138.0,19.4,9576,Retailing,Specialty Retailers: Apparel
971,Finish Line,1934.0,-18.2,8200,Retailing,Specialty Retailers: Apparel
989,Barnes & Noble Education,1874.0,5.4,13375,Retailing,Specialty Retailers: Other
992,Childrens Place,1870.0,84.7,9800,Retailing,Specialty Retailers: Apparel

In [27]:
fortune[fortune['Sector']=='Retailing']['Revenues'].head()

0     500343.0
7     177866.0
14    129025.0
22    100904.0
38     71879.0
Name: Revenues, dtype: float64

In [29]:
fortune[fortune['Sector']=='Retailing']['Revenues'].mean()

np.float64(21874.714285714286)

In [30]:
sectors = fortune.groupby('Sector')

In [31]:
sectors

In [32]:
len(sectors)

21

In [33]:
fortune['Sector'].nunique()

21

In [34]:
sectors.size()

Sector
Aerospace & Defense               25
Apparel                           14
Business Services                 53
Chemicals                         33
Energy                           107
Engineering & Construction        27
Financials                       155
Food &  Drug Stores               12
Food, Beverages & Tobacco         37
Health Care                       71
Hotels, Restaurants & Leisure     26
Household Products                28
Industrials                       49
Materials                         45
Media                             25
Motor Vehicles & Parts            19
Retailing                         77
Technology                       103
Telecommunications                10
Transportation                    40
Wholesalers                       44
dtype: int64

In [35]:
sectors.groups

{'Aerospace & Defense': [26, 50, 58, 98, 117, 118, 207, 224, 275, 380, 404, 406, 414, 540, 660, 661, 806, 829, 884, 930, 954, 955, 959, 975, 988], 'Apparel': [88, 241, 331, 420, 432, 526, 529, 554, 587, 678, 766, 774, 835, 861], 'Business Services': [142, 160, 187, 199, 201, 221, 235, 242, 253, 295, 325, 358, 364, 423, 462, 465, 486, 493, 497, 499, 502, 510, 528, 567, 577, 584, 591, 599, 604, 618, 649, 686, 691, 692, 700, 702, 712, 720, 738, 744, 771, 802, 810, 825, 879, 888, 894, 895, 898, 905, 922, 972, 997], 'Chemicals': [46, 189, 190, 198, 214, 263, 281, 309, 344, 351, 381, 447, 450, 454, 527, 593, 623, 648, 671, 672, 679, 704, 722, 740, 790, 836, 865, 872, 908, 932, 958, 963, 978], 'Energy': [1, 12, 27, 30, 40, 63, 89, 90, 91, 94, 104, 114, 124, 125, 134, 145, 166, 167, 175, 184, 205, 212, 213, 217, 218, 219, 222, 231, 232, 243, 248, 254, 256, 265, 268, 269, 270, 273, 307, 313, 326, 333, 335, 343, 352, 363, 371, 379, 383, 384, 387, 428, 437, 452, 456, 488, 490, 496, 498, 500, 517, 534, 537, 559, 563, 582, 603, 617, 635, 638, 639, 647, 653, 668, 681, 682, 689, 708, 719, 723, 739, 768, 791, 798, 805, 812, 816, 818, 820, 826, 844, 859, 860, 866, 869, 885, 890, 901, 917, 934, ...], 'Engineering & Construction': [152, 163, 210, 229, 296, 315, 338, 340, 367, 427, 443, 479, 541, 569, 588, 615, 705, 736, 737, 764, 779, 815, 841, 852, 962, 982, 986], 'Financials': [2, 19, 20, 23, 25, 31, 35, 37, 42, 51, 59, 65, 66, 67, 68, 69, 78, 83, 85, 92, 99, 100, 102, 103, 105, 111, 121, 135, 136, 155, 164, 172, 174, 204, 206, 209, 211, 216, 233, 236, 238, 240, 249, 251, 252, 258, 262, 266, 298, 301, 302, 306, 310, 312, 329, 336, 342, 347, 355, 365, 368, 374, 375, 377, 397, 411, 412, 418, 430, 434, 436, 439, 440, 449, 453, 457, 459, 461, 463, 466, 468, 469, 475, 476, 482, 483, 485, 492, 501, 513, 514, 533, 539, 543, 562, 570, 572, 576, 579, 581, ...], 'Food &  Drug Stores': [16, 18, 52, 87, 93, 179, 549, 552, 600, 667, 839, 941], 'Food, Beverages & Tobacco': [44, 47, 79, 86, 95, 107, 113, 116, 153, 181, 215, 225, 274, 320, 322, 357, 361, 378, 382, 385, 417, 445, 477, 480, 511, 538, 575, 611, 628, 633, 683, 694, 717, 734, 759, 900, 937], 'Health Care': [4, 6, 24, 28, 36, 48, 55, 56, 60, 62, 72, 77, 109, 110, 115, 128, 129, 144, 146, 151, 159, 161, 169, 178, 197, 223, 239, 244, 250, 267, 282, 285, 303, 327, 360, 366, 389, 415, 472, 474, 503, 506, 518, 542, 555, 560, 602, 605, 655, 669, 673, 718, 724, 742, 753, 754, 782, 795, 830, 845, 915, 921, 925, 935, 936, 939, 956, 960, 994, 996, 998], 'Hotels, Restaurants & Leisure': [126, 130, 131, 226, 279, 323, 395, 396, 446, 471, 478, 535, 548, 556, 583, 713, 714, 721, 741, 775, 817, 851, 891, 903, 965, 984], 'Household Products': [41, 162, 183, 195, 227, 257, 314, 370, 372, 421, 467, 484, 508, 512, 532, 608, 622, 727, 778, 794, 821, 875, 881, 882, 893, 912, 946, 967], 'Industrials': [17, 64, 76, 96, 101, 139, 148, 154, 177, 203, 255, 292, 341, 346, 359, 413, 419, 444, 546, 571, 601, 616, 619, 620, 626, 627, 631, 634, 664, 687, 730, 731, 750, 776, 803, 813, 827, 850, 853, 854, 857, 864, 878, 887, 938, 943, 951, 966, 981], 'Materials': [123, 150, 193, 245, 261, 276, 304, 311, 337, 393, 398, 399, 403, 409, 426, 435, 441, 455, 460, 516, 522, 524, 564, 594, 595, 596, 606, 609, 614, 624, 641, 662, 663, 685, 695, 707, 729, 756, 781, 786, 833, 837, 945, 957, 974], 'Media': [54, 97, 108, 196, 220, 289, 349, 376, 405, 408, 451, 592, 645, 650, 654, 710, 715, 728, 735, 767, 785, 819, 847, 961, 993], 'Motor Vehicles & Parts': [9, 10, 147, 186, 259, 288, 300, 319, 391, 392, 448, 643, 699, 716, 758, 886, 889, 920, 940], 'Retailing': [0, 7, 14, 22, 38, 39, 71, 84, 119, 122, 133, 137, 138, 156, 171, 173, 180, 182, 208, 230, 234, 247, 271, 272, 277, 278, 280, 287, 293, 294, 297, 316, 321, 328, 332, 334, 339, 362, 390, 422, 424, 433, 438, 458, 464, 470, 504, 507, 509, 545, 547, 580, 589, 610, 612, 621, 644, 665, 680, 698, 732, 745, 746, 770, 777, 792, 822, 846, 855, 856, 858, 880, 909, 926, 971, 989, 992], 'Technology': [3, 21, 29, 33, 34, 45, 57, 61, 75, 81, 106, 132, 143, 149, 157, 158, 188, 191, 194, 200, 228, 260, 284, 290, 291, 305, 308, 353, 373, 388, 400, 402, 410, 416, 431, 442, 481, 491, 494, 505, 515, 519, 523, 525, 536, 544, 550, 551, 553, 557, 558, 573, 578, 585, 586, 597, 636, 646, 656, 666, 674, 696, 697, 703, 709, 726, 752, 755, 763, 769, 780, 783, 787, 788, 797, 799, 807, 823, 824, 828, 834, 842, 843, 849, 862, 868, 871, 874, 876, 892, 897, 902, 919, 924, 927, 931, 944, 948, 969, 970, ...], 'Telecommunications': [8, 15, 32, 73, 165, 202, 324, 473, 520, 907], 'Transportation': [43, 49, 70, 74, 80, 140, 141, 185, 192, 264, 283, 354, 386, 394, 401, 407, 487, 495, 530, 531, 566, 598, 632, 637, 675, 688, 706, 762, 793, 801, 814, 848, 904, 906, 914, 918, 928, 933, 947, 968], 'Wholesalers': [5, 11, 13, 53, 82, 112, 120, 127, 168, 170, 176, 237, 246, 286, 299, 317, 318, 330, 345, 348, 350, 356, 369, 425, 429, 489, 521, 561, 565, 568, 574, 642, 652, 670, 684, 748, 757, 773, 800, 809, 870, 910, 942, 995]}

In [36]:
fortune.loc[26]

Company                     Boeing
Revenues                   93392.0
Profits                     8197.0
Employees                   140800
Sector         Aerospace & Defense
Industry     Aerospace and Defense
Name: 26, dtype: object

In [37]:
sectors.first()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Boeing,93392.0,8197.0,140800,Aerospace and Defense
Apparel,Nike,34350.0,4240.0,74400,Apparel
Business Services,ManpowerGroup,21034.0,545.4,29000,Temporary Help
Chemicals,DowDuPont,62683.0,1460.0,98000,Chemicals
Energy,Exxon Mobil,244363.0,19710.0,71200,Petroleum Refining
Engineering & Construction,Fluor,19521.0,191.4,56706,"Engineering, Construction"
Financials,Berkshire Hathaway,242137.0,44940.0,377000,Insurance: Property and Casualty (Stock)
Food & Drug Stores,Kroger,122662.0,1907.0,449000,Food and Drug Stores
"Food, Beverages & Tobacco",PepsiCo,63525.0,4857.0,263000,Food Consumer Products
Health Care,UnitedHealth Group,201159.0,10558.0,260000,Health Care: Insurance and Managed Care
"Hotels, Restaurants & Leisure",Marriott International,22894.0,1372.0,177000,"Hotels, Casinos, Resorts"
Household Products,Procter & Gamble,66217.0,15326.0,95000,Household and Personal Products
Industrials,General Electric,122274.0,-5786.0,313000,Industrial Machinery
Materials,International Paper,23302.0,2144.0,56000,"Packaging, Containers"
Media,Disney,55137.0,8980.0,199000,Entertainment
Motor Vehicles & Parts,General Motors,157311.0,-3864.0,180000,Motor Vehicles and Parts
Retailing,Walmart,500343.0,9862.0,2300000,General Merchandisers
Technology,Apple,229234.0,48351.0,123000,"Computers, Office Equipment"
Telecommunications,AT&T,160546.0,29450.0,254000,Telecommunications
Transportation,UPS,65872.0,4910.0,346415,"Mail, Package, and Freight Delivery"
Wholesalers,McKesson,198533.0,5070.0,64500,Wholesalers: Health Care

In [38]:
sectors.last()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Aerojet Rocketdyne Holdings,1877.0,-9.2,5157,Aerospace and Defense
Apparel,Wolverine World Wide,2350.0,0.3,3700,Apparel
Business Services,CoreLogic,1851.0,152.2,5900,Financial Data Services
Chemicals,Stepan,1925.0,91.6,2096,Chemicals
Energy,Superior Energy Services,1874.0,-205.9,6400,"Oil and Gas Equipment, Services"
Engineering & Construction,TopBuild,1906.0,158.1,8400,"Engineering, Construction"
Financials,HCP,1848.0,414.2,190,Real estate
Food & Drug Stores,Freds,2064.0,-140.3,7324,Food and Drug Stores
"Food, Beverages & Tobacco",Universal,2071.0,106.3,24000,Tobacco
Health Care,Ensign Group,1849.0,40.5,21301,Health Care: Medical Facilities
"Hotels, Restaurants & Leisure",Vail Resorts,1907.0,210.6,20150,"Hotels, Casinos, Resorts"
Household Products,ACCO Brands,1949.0,131.7,6620,"Home Equipment, Furnishings"
Industrials,Rexnord,1918.0,74.1,8000,Industrial Machinery
Materials,Summit Materials,1933.0,121.8,6000,"Building Materials, Glass"
Media,Tribune Media,1867.0,194.1,6000,Entertainment
Motor Vehicles & Parts,Tower International,2066.0,47.6,7600,Motor Vehicles and Parts
Retailing,Childrens Place,1870.0,84.7,9800,Specialty Retailers: Apparel
Technology,VeriFone Systems,1871.0,-173.8,5600,Financial Data Services
Telecommunications,Zayo Group Holdings,2200.0,85.7,3794,Telecommunications
Transportation,Echo Global Logistics,1943.0,12.6,2453,Transportation and Logistics
Wholesalers,SiteOne Landscape Supply,1862.0,54.6,3664,Wholesalers: Diversified

In [42]:
sectors.nth(0)

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care
5,McKesson,198533.0,5070.0,64500,Wholesalers,Wholesalers: Health Care
8,AT&T,160546.0,29450.0,254000,Telecommunications,Telecommunications
9,General Motors,157311.0,-3864.0,180000,Motor Vehicles & Parts,Motor Vehicles and Parts
16,Kroger,122662.0,1907.0,449000,Food & Drug Stores,Food and Drug Stores
17,General Electric,122274.0,-5786.0,313000,Industrials,Industrial Machinery
26,Boeing,93392.0,8197.0,140800,Aerospace & Defense,Aerospace and Defense
41,Procter & Gamble,66217.0,15326.0,95000,Household Products,Household and Personal Products
43,UPS,65872.0,4910.0,346415,Transportation,"Mail, Package, and Freight Delivery"
44,PepsiCo,63525.0,4857.0,263000,"Food, Beverages & Tobacco",Food Consumer Products
46,DowDuPont,62683.0,1460.0,98000,Chemicals,Chemicals
54,Disney,55137.0,8980.0,199000,Media,Entertainment
88,Nike,34350.0,4240.0,74400,Apparel,Apparel
123,International Paper,23302.0,2144.0,56000,Materials,"Packaging, Containers"
126,Marriott International,22894.0,1372.0,177000,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
142,ManpowerGroup,21034.0,545.4,29000,Business Services,Temporary Help
152,Fluor,19521.0,191.4,56706,Engineering & Construction,"Engineering, Construction"

In [43]:
sectors.nth(1)

,Company,Revenues,Profits,Employees,Sector,Industry
6,CVS Health,184765.0,6622.0,203000,Health Care,Health Care: Pharmacy and Other Services
7,Amazon.com,177866.0,3033.0,566000,Retailing,Internet Services and Retailing
10,Ford Motor,156776.0,7602.0,202000,Motor Vehicles & Parts,Motor Vehicles and Parts
11,AmerisourceBergen,153144.0,364.5,19500,Wholesalers,Wholesalers: Health Care
12,Chevron,134533.0,9195.0,51900,Energy,Petroleum Refining
15,Verizon,126034.0,30101.0,155400,Telecommunications,Telecommunications
18,Walgreens Boots Alliance,118214.0,4078.0,290000,Food & Drug Stores,Food and Drug Stores
19,JPMorgan Chase,113899.0,24441.0,252539,Financials,Commercial Banks
21,Alphabet,110855.0,12662.0,80110,Technology,Internet Services and Retailing
47,Archer Daniels Midland,60828.0,1595.0,31300,"Food, Beverages & Tobacco",Food Production
49,FedEx,60319.0,2997.0,357000,Transportation,"Mail, Package, and Freight Delivery"
50,United Technologies,59837.0,4552.0,204700,Aerospace & Defense,Aerospace and Defense
64,Caterpillar,45462.0,754.0,98400,Industrials,Construction and Farm Machinery
97,Time Warner,31271.0,5247.0,26000,Media,Entertainment
130,McDonalds,22820.0,5192.3,235000,"Hotels, Restaurants & Leisure",Food Services
150,Nucor,20252.0,1318.7,25100,Materials,Metals
160,Visa,18358.0,6699.0,15000,Business Services,Financial Data Services
162,Kimberly-Clark,18259.0,2278.0,42000,Household Products,Household and Personal Products
163,AECOM,18203.0,339.4,87000,Engineering & Construction,"Engineering, Construction"
189,Sherwin-Williams,14984.0,1772.3,52695,Chemicals,Chemicals
241,VF,12400.0,614.9,69000,Apparel,Apparel

In [44]:
fortune[fortune['Sector']=='Technology']

,Company,Revenues,Profits,Employees,Sector,Industry
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
21,Alphabet,110855.0,12662.0,80110,Technology,Internet Services and Retailing
29,Microsoft,89950.0,21204.0,124000,Technology,Computer Software
33,IBM,79139.0,5753.0,397800,Technology,Information Technology Services
34,Dell Technologies,78660.0,-3728.0,145000,Technology,"Computers, Office Equipment"
...,...,...,...,...,...,...
969,Cadence Design Systems,1943.0,204.1,7214,Technology,Computer Software
970,Nuance Communications,1939.0,-151.0,11600,Technology,Computer Software
973,ServiceNow,1933.0,-149.1,6222,Technology,Computer Software
983,MKS Instruments,1916.0,339.1,4923,Technology,Semiconductors and Other Electronic Components
991,VeriFone Systems,1871.0,-173.8,5600,Technology,Financial Data Services

In [49]:
sectors.head(2)

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care
5,McKesson,198533.0,5070.0,64500,Wholesalers,Wholesalers: Health Care
6,CVS Health,184765.0,6622.0,203000,Health Care,Health Care: Pharmacy and Other Services
7,Amazon.com,177866.0,3033.0,566000,Retailing,Internet Services and Retailing
8,AT&T,160546.0,29450.0,254000,Telecommunications,Telecommunications
9,General Motors,157311.0,-3864.0,180000,Motor Vehicles & Parts,Motor Vehicles and Parts
10,Ford Motor,156776.0,7602.0,202000,Motor Vehicles & Parts,Motor Vehicles and Parts
11,AmerisourceBergen,153144.0,364.5,19500,Wholesalers,Wholesalers: Health Care
12,Chevron,134533.0,9195.0,51900,Energy,Petroleum Refining
15,Verizon,126034.0,30101.0,155400,Telecommunications,Telecommunications
16,Kroger,122662.0,1907.0,449000,Food & Drug Stores,Food and Drug Stores
17,General Electric,122274.0,-5786.0,313000,Industrials,Industrial Machinery
18,Walgreens Boots Alliance,118214.0,4078.0,290000,Food & Drug Stores,Food and Drug Stores
19,JPMorgan Chase,113899.0,24441.0,252539,Financials,Commercial Banks
21,Alphabet,110855.0,12662.0,80110,Technology,Internet Services and Retailing
26,Boeing,93392.0,8197.0,140800,Aerospace & Defense,Aerospace and Defense
41,Procter & Gamble,66217.0,15326.0,95000,Household Products,Household and Personal Products
43,UPS,65872.0,4910.0,346415,Transportation,"Mail, Package, and Freight Delivery"
44,PepsiCo,63525.0,4857.0,263000,"Food, Beverages & Tobacco",Food Consumer Products
46,DowDuPont,62683.0,1460.0,98000,Chemicals,Chemicals
47,Archer Daniels Midland,60828.0,1595.0,31300,"Food, Beverages & Tobacco",Food Production
49,FedEx,60319.0,2997.0,357000,Transportation,"Mail, Package, and Freight Delivery"
50,United Technologies,59837.0,4552.0,204700,Aerospace & Defense,Aerospace and Defense
54,Disney,55137.0,8980.0,199000,Media,Entertainment
64,Caterpillar,45462.0,754.0,98400,Industrials,Construction and Farm Machinery
88,Nike,34350.0,4240.0,74400,Apparel,Apparel
97,Time Warner,31271.0,5247.0,26000,Media,Entertainment
123,International Paper,23302.0,2144.0,56000,Materials,"Packaging, Containers"
126,Marriott International,22894.0,1372.0,177000,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
130,McDonalds,22820.0,5192.3,235000,"Hotels, Restaurants & Leisure",Food Services
142,ManpowerGroup,21034.0,545.4,29000,Business Services,Temporary Help
150,Nucor,20252.0,1318.7,25100,Materials,Metals
152,Fluor,19521.0,191.4,56706,Engineering & Construction,"Engineering, Construction"
160,Visa,18358.0,6699.0,15000,Business Services,Financial Data Services
162,Kimberly-Clark,18259.0,2278.0,42000,Household Products,Household and Personal Products
163,AECOM,18203.0,339.4,87000,Engineering & Construction,"Engineering, Construction"
189,Sherwin-Williams,14984.0,1772.3,52695,Chemicals,Chemicals
241,VF,12400.0,614.9,69000,Apparel,Apparel

In [50]:
sectors.get_group('Materials')

,Company,Revenues,Profits,Employees,Sector,Industry
123,International Paper,23302.0,2144.0,56000,Materials,"Packaging, Containers"
150,Nucor,20252.0,1318.7,25100,Materials,Metals
193,WestRock,14860.0,708.2,44800,Materials,"Packaging, Containers"
245,United States Steel,12250.0,387.0,29200,Materials,Metals
261,Alcoa,11652.0,217.0,14600,Materials,Metals
276,Ball,10983.0,374.0,18300,Materials,"Packaging, Containers"
304,Reliance Steel & Aluminum,9721.0,613.4,14900,Materials,Metals
311,Steel Dynamics,9539.0,812.7,7635,Materials,Metals
337,Crown Holdings,8698.0,323.0,24342,Materials,"Packaging, Containers"
393,Weyerhaeuser,7196.0,582.0,9300,Materials,Forest and Paper Products
398,Berry Global Group,7095.0,340.0,23000,Materials,"Packaging, Containers"
399,Builders FirstSource,7034.0,38.8,15000,Materials,"Building Materials, Glass"
403,A-Mark Precious Metals,6990.0,7.1,126,Materials,Miscellaneous
409,Owens-Illinois,6869.0,180.0,26500,Materials,"Packaging, Containers"
426,Avery Dennison,6614.0,281.8,30000,Materials,"Packaging, Containers"
435,Packaging Corp. of America,6445.0,668.6,14600,Materials,"Packaging, Containers"
441,Owens Corning,6384.0,289.0,17000,Materials,"Building Materials, Glass"
455,Sealed Air,6131.0,814.9,15000,Materials,"Packaging, Containers"
460,AK Steel Holding,6081.0,6.2,9200,Materials,Metals
516,Domtar,5157.0,-258.0,10000,Materials,Forest and Paper Products
522,Sonoco Products,5037.0,175.3,21000,Materials,"Packaging, Containers"
524,Commercial Metals,4999.0,46.3,8797,Materials,Metals
564,Graphic Packaging Holding,4404.0,300.2,13000,Materials,"Packaging, Containers"
594,Carlisle,4090.0,365.5,14800,Materials,"Building Materials, Glass"
595,Silgan Holdings,4090.0,269.7,12515,Materials,"Packaging, Containers"
596,Bemis,4046.0,94.0,16582,Materials,"Packaging, Containers"
606,Martin Marietta Materials,3966.0,713.3,8406,Materials,"Building Materials, Glass"
609,Universal Forest Products,3941.0,119.5,10000,Materials,"Building Materials, Glass"
614,Vulcan Materials,3890.0,601.2,8287,Materials,"Building Materials, Glass"
624,JELD-WEN Holding,3764.0,10.8,21000,Materials,"Building Materials, Glass"
641,Greif,3638.0,118.6,13000,Materials,"Packaging, Containers"
662,Allegheny Technologies,3525.0,-91.9,8600,Materials,Metals
663,Resolute Forest Products,3513.0,-84.0,7700,Materials,Forest and Paper Products
685,Ryerson Holding,3365.0,17.1,3600,Materials,Metals
695,KapStone Paper & Packaging,3316.0,243.5,6400,Materials,"Packaging, Containers"
707,USG,3204.0,88.0,6800,Materials,"Building Materials, Glass"
729,Worthington Industries,3014.0,204.5,10000,Materials,Metals
756,Aleris,2858.0,-210.6,5400,Materials,Metals
781,Valmont Industries,2746.0,116.2,10690,Materials,Metals
786,Louisiana-Pacific,2734.0,389.8,5000,Materials,"Building Materials, Glass"
833,AptarGroup,2469.0,220.0,13200,Materials,"Packaging, Containers"
837,Verso,2461.0,-30.0,4200,Materials,Forest and Paper Products
945,Ply Gem Holdings,2056.0,68.3,9471,Materials,"Building Materials, Glass"
957,Griffon,1986.0,14.9,4700,Materials,"Building Materials, Glass"
974,Summit Materials,1933.0,121.8,6000,Materials,"Building Materials, Glass"

In [56]:
fortune.groupby('Sector').get_group('Materials')

,Company,Revenues,Profits,Employees,Sector,Industry
123,International Paper,23302.0,2144.0,56000,Materials,"Packaging, Containers"
150,Nucor,20252.0,1318.7,25100,Materials,Metals
193,WestRock,14860.0,708.2,44800,Materials,"Packaging, Containers"
245,United States Steel,12250.0,387.0,29200,Materials,Metals
261,Alcoa,11652.0,217.0,14600,Materials,Metals
276,Ball,10983.0,374.0,18300,Materials,"Packaging, Containers"
304,Reliance Steel & Aluminum,9721.0,613.4,14900,Materials,Metals
311,Steel Dynamics,9539.0,812.7,7635,Materials,Metals
337,Crown Holdings,8698.0,323.0,24342,Materials,"Packaging, Containers"
393,Weyerhaeuser,7196.0,582.0,9300,Materials,Forest and Paper Products
398,Berry Global Group,7095.0,340.0,23000,Materials,"Packaging, Containers"
399,Builders FirstSource,7034.0,38.8,15000,Materials,"Building Materials, Glass"
403,A-Mark Precious Metals,6990.0,7.1,126,Materials,Miscellaneous
409,Owens-Illinois,6869.0,180.0,26500,Materials,"Packaging, Containers"
426,Avery Dennison,6614.0,281.8,30000,Materials,"Packaging, Containers"
435,Packaging Corp. of America,6445.0,668.6,14600,Materials,"Packaging, Containers"
441,Owens Corning,6384.0,289.0,17000,Materials,"Building Materials, Glass"
455,Sealed Air,6131.0,814.9,15000,Materials,"Packaging, Containers"
460,AK Steel Holding,6081.0,6.2,9200,Materials,Metals
516,Domtar,5157.0,-258.0,10000,Materials,Forest and Paper Products
522,Sonoco Products,5037.0,175.3,21000,Materials,"Packaging, Containers"
524,Commercial Metals,4999.0,46.3,8797,Materials,Metals
564,Graphic Packaging Holding,4404.0,300.2,13000,Materials,"Packaging, Containers"
594,Carlisle,4090.0,365.5,14800,Materials,"Building Materials, Glass"
595,Silgan Holdings,4090.0,269.7,12515,Materials,"Packaging, Containers"
596,Bemis,4046.0,94.0,16582,Materials,"Packaging, Containers"
606,Martin Marietta Materials,3966.0,713.3,8406,Materials,"Building Materials, Glass"
609,Universal Forest Products,3941.0,119.5,10000,Materials,"Building Materials, Glass"
614,Vulcan Materials,3890.0,601.2,8287,Materials,"Building Materials, Glass"
624,JELD-WEN Holding,3764.0,10.8,21000,Materials,"Building Materials, Glass"
641,Greif,3638.0,118.6,13000,Materials,"Packaging, Containers"
662,Allegheny Technologies,3525.0,-91.9,8600,Materials,Metals
663,Resolute Forest Products,3513.0,-84.0,7700,Materials,Forest and Paper Products
685,Ryerson Holding,3365.0,17.1,3600,Materials,Metals
695,KapStone Paper & Packaging,3316.0,243.5,6400,Materials,"Packaging, Containers"
707,USG,3204.0,88.0,6800,Materials,"Building Materials, Glass"
729,Worthington Industries,3014.0,204.5,10000,Materials,Metals
756,Aleris,2858.0,-210.6,5400,Materials,Metals
781,Valmont Industries,2746.0,116.2,10690,Materials,Metals
786,Louisiana-Pacific,2734.0,389.8,5000,Materials,"Building Materials, Glass"
833,AptarGroup,2469.0,220.0,13200,Materials,"Packaging, Containers"
837,Verso,2461.0,-30.0,4200,Materials,Forest and Paper Products
945,Ply Gem Holdings,2056.0,68.3,9471,Materials,"Building Materials, Glass"
957,Griffon,1986.0,14.9,4700,Materials,"Building Materials, Glass"
974,Summit Materials,1933.0,121.8,6000,Materials,"Building Materials, Glass"

In [61]:
sectors['Revenues'].sum(numeric_only=True)

Sector
Aerospace & Defense               383835.0
Apparel                           101157.3
Business Services                 316090.0
Chemicals                         251151.0
Energy                           1543507.2
Engineering & Construction        172782.0
Financials                       2442480.0
Food &  Drug Stores               405468.0
Food, Beverages & Tobacco         510232.0
Health Care                      1507991.4
Hotels, Restaurants & Leisure     179825.0
Household Products                231779.8
Industrials                       520140.0
Materials                         278298.0
Media                             230487.4
Motor Vehicles & Parts            433535.0
Retailing                        1684353.0
Technology                       1374822.3
Telecommunications                466959.0
Transportation                    455160.0
Wholesalers                       888149.0
Name: Revenues, dtype: float64

In [66]:
sectors.get_group('Transportation').loc[:, 'Revenues'].sum()

np.float64(455160.0)

In [67]:
sectors.mean(numeric_only=True)

                                   Revenues      Profits      Employees
Sector
Aerospace & Defense            15353.400000  1069.340000   40404.960000
Apparel                         7225.521429   453.621429   25407.071429
Business Services               5963.962264   701.494340   30075.452830
Chemicals                       7610.636364   620.454545   14364.242424
Energy                         14425.300935   805.373585    9170.158879
Engineering & Construction      6399.333333   263.740741   15583.148148
Financials                     15757.935484  1704.861290   22581.412903
Food &  Drug Stores            33789.000000   703.358333  116506.166667
Food, Beverages & Tobacco      13790.054054  1483.851351   29170.702703
Health Care                    21239.315493  1306.916901   41847.732394
Hotels, Restaurants & Leisure   6916.346154   819.442308   88628.346154
Household Products              8277.850000   990.242857   24103.428571
Industrials                    10615.102041   390.087755   31961.428571
Materials                       6184.400000   305.120000   14527.800000
Media                           9219.496000   920.796000   21839.400000
Motor Vehicles & Parts         22817.631579   361.110526   49662.210526
Retailing                      21874.714286   723.470130   88320.233766
Technology                     13347.789320  1743.959804   31036.961165
Telecommunications             46695.900000  9196.580000   78560.900000
Transportation                 11379.000000  1324.007500   41302.825000
Wholesalers                    20185.204545   355.850000   16913.068182

In [68]:
sectors['Revenues'].sum()

Sector
Aerospace & Defense               383835.0
Apparel                           101157.3
Business Services                 316090.0
Chemicals                         251151.0
Energy                           1543507.2
Engineering & Construction        172782.0
Financials                       2442480.0
Food &  Drug Stores               405468.0
Food, Beverages & Tobacco         510232.0
Health Care                      1507991.4
Hotels, Restaurants & Leisure     179825.0
Household Products                231779.8
Industrials                       520140.0
Materials                         278298.0
Media                             230487.4
Motor Vehicles & Parts            433535.0
Retailing                        1684353.0
Technology                       1374822.3
Telecommunications                466959.0
Transportation                    455160.0
Wholesalers                       888149.0
Name: Revenues, dtype: float64

In [69]:
aggregation = {
    'Revenues':'min',
    'Profits':'max',
    'Employees':'mean'
}
sectors.agg(func=aggregation)

                               Revenues  Profits      Employees
Sector
Aerospace & Defense              1877.0   8197.0   40404.960000
Apparel                          2350.0   4240.0   25407.071429
Business Services                1851.0   6699.0   30075.452830
Chemicals                        1925.0   3000.4   14364.242424
Energy                           1874.0  19710.0    9170.158879
Engineering & Construction       1906.0   1038.4   15583.148148
Financials                       1848.0  44940.0   22581.412903
Food &  Drug Stores              2064.0   4078.0  116506.166667
Food, Beverages & Tobacco        2071.0  10999.0   29170.702703
Health Care                      1849.0  21308.0   41847.732394
Hotels, Restaurants & Leisure    1907.0   5192.3   88628.346154
Household Products               1949.0  15326.0   24103.428571
Industrials                      1918.0   4858.0   31961.428571
Materials                        1933.0   2144.0   14527.800000
Media                            1867.0   8980.0   21839.400000
Motor Vehicles & Parts           2066.0   7602.0   49662.210526
Retailing                        1870.0   9862.0   88320.233766
Technology                       1871.0  48351.0   31036.961165
Telecommunications               2200.0  30101.0   78560.900000
Transportation                   1943.0  10712.0   41302.825000
Wholesalers                      1862.0   5070.0   16913.068182

In [72]:
sectors['Employees'].agg('mean')

Sector
Aerospace & Defense               40404.960000
Apparel                           25407.071429
Business Services                 30075.452830
Chemicals                         14364.242424
Energy                             9170.158879
Engineering & Construction        15583.148148
Financials                        22581.412903
Food &  Drug Stores              116506.166667
Food, Beverages & Tobacco         29170.702703
Health Care                       41847.732394
Hotels, Restaurants & Leisure     88628.346154
Household Products                24103.428571
Industrials                       31961.428571
Materials                         14527.800000
Media                             21839.400000
Motor Vehicles & Parts            49662.210526
Retailing                         88320.233766
Technology                        31036.961165
Telecommunications                78560.900000
Transportation                    41302.825000
Wholesalers                       16913.068182
Name: Employees, dtype: float64

In [73]:
fortune.nlargest(n=5, columns='Profits')

,Company,Revenues,Profits,Employees,Sector,Industry
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
15,Verizon,126034.0,30101.0,155400,Telecommunications,Telecommunications
8,AT&T,160546.0,29450.0,254000,Telecommunications,Telecommunications
19,JPMorgan Chase,113899.0,24441.0,252539,Financials,Commercial Banks

In [74]:
def get_largest_row(df):
    return df.nlargest(1, 'Revenues')

In [75]:
sectors.apply(get_largest_row)

/var/folders/yd/4k8th6097mb8w26m8__j7j140000gn/T/ipykernel_7808/3802245821.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sectors.apply(get_largest_row)

,,Company,Revenues,Profits,Employees,Sector,Industry
Sector,,,,,,,
Aerospace & Defense,26,Boeing,93392.0,8197.0,140800,Aerospace & Defense,Aerospace and Defense
Apparel,88,Nike,34350.0,4240.0,74400,Apparel,Apparel
Business Services,142,ManpowerGroup,21034.0,545.4,29000,Business Services,Temporary Help
Chemicals,46,DowDuPont,62683.0,1460.0,98000,Chemicals,Chemicals
Energy,1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
Engineering & Construction,152,Fluor,19521.0,191.4,56706,Engineering & Construction,"Engineering, Construction"
Financials,2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
Food & Drug Stores,16,Kroger,122662.0,1907.0,449000,Food & Drug Stores,Food and Drug Stores
"Food, Beverages & Tobacco",44,PepsiCo,63525.0,4857.0,263000,"Food, Beverages & Tobacco",Food Consumer Products
Health Care,4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care
"Hotels, Restaurants & Leisure",126,Marriott International,22894.0,1372.0,177000,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
Household Products,41,Procter & Gamble,66217.0,15326.0,95000,Household Products,Household and Personal Products
Industrials,17,General Electric,122274.0,-5786.0,313000,Industrials,Industrial Machinery
Materials,123,International Paper,23302.0,2144.0,56000,Materials,"Packaging, Containers"
Media,54,Disney,55137.0,8980.0,199000,Media,Entertainment
Motor Vehicles & Parts,9,General Motors,157311.0,-3864.0,180000,Motor Vehicles & Parts,Motor Vehicles and Parts
Retailing,0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
Technology,3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
Telecommunications,8,AT&T,160546.0,29450.0,254000,Telecommunications,Telecommunications
Transportation,43,UPS,65872.0,4910.0,346415,Transportation,"Mail, Package, and Freight Delivery"
Wholesalers,5,McKesson,198533.0,5070.0,64500,Wholesalers,Wholesalers: Health Care

In [76]:
sector_and_industry = fortune.groupby(by=['Sector', 'Industry'])
sector_and_industry.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            25
Apparel              Apparel                                          14
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         2
                                                                      ..
Transportation       Trucking, Truck Leasing                          11
Wholesalers          Wholesalers: Diversified                         24
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
                     Wholesalers: Health Care                          6
Length: 82, dtype: int64

In [77]:
sector_and_industry.get_group(('Business Services', 'Education'))

,Company,Revenues,Profits,Employees,Sector,Industry
567,Laureate Education,4378.0,91.5,54500,Business Services,Education
810,Graham Holdings,2592.0,302.0,16153,Business Services,Education

In [78]:
sector_and_industry.sum(numeric_only=True)

                                                                   Revenues  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                          383835.0
Apparel             Apparel                                        101157.3
Business Services   Advertising, marketing                          23156.0
                    Diversified Outsourcing Services                74175.0
                    Education                                        6970.0
...                                                                     ...
Transportation      Trucking, Truck Leasing                         43676.0
Wholesalers         Wholesalers: Diversified                       130984.0
                    Wholesalers: Electronics and Office Equipment  122231.0
                    Wholesalers: Food and Grocery                  125908.0
                    Wholesalers: Health Care                       509026.0

                                                                   Profits  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                          26733.5
Apparel             Apparel                                         6350.7
Business Services   Advertising, marketing                          1667.4
                    Diversified Outsourcing Services                5043.7
                    Education                                        393.5
...                                                                    ...
Transportation      Trucking, Truck Leasing                         3535.5
Wholesalers         Wholesalers: Diversified                        5231.5
                    Wholesalers: Electronics and Office Equipment   1259.4
                    Wholesalers: Food and Grocery                   1794.0
                    Wholesalers: Health Care                        7372.5

                                                                   Employees
Sector              Industry
Aerospace & Defense Aerospace and Defense                            1010124
Apparel             Apparel                                           355699
Business Services   Advertising, marketing                            127500
                    Diversified Outsourcing Services                  858600
                    Education                                          70653
...                                                                      ...
Transportation      Trucking, Truck Leasing                           208312
Wholesalers         Wholesalers: Diversified                          262390
                    Wholesalers: Electronics and Office Equipment     183518
                    Wholesalers: Food and Grocery                     135767
                    Wholesalers: Health Care                          162500

[82 rows x 3 columns]

In [79]:
sector_and_industry['Revenues'].mean()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            15353.400000
Apparel              Apparel                                           7225.521429
Business Services    Advertising, marketing                           11578.000000
                     Diversified Outsourcing Services                  5298.214286
                     Education                                         3485.000000
                                                                          ...
Transportation       Trucking, Truck Leasing                           3970.545455
Wholesalers          Wholesalers: Diversified                          5457.666667
                     Wholesalers: Electronics and Office Equipment    15278.875000
                     Wholesalers: Food and Grocery                    20984.666667
                     Wholesalers: Health Care                         84837.666667
Name: Revenues, Length: 82, dtype: float64